const actionTypes = {
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    INIT_INGREDIENTS: 'INIT_INGREDIENTS',
    FETCH_INGREDIENTS_FAILED: 'FETCH_INGREDIENTS_FAILED',
    PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
    PURCHASE_BURGER_FAILED: 'PURCHASE_BURGER_FAILED',
    PURCHASE_BURGER_START: 'PURCHASE_BURGER_START',
    PURCHASE_BURGER_INIT: 'PURCHASE_BURGER_INIT',
    FETCH_ORDERS_START: 'FETCH_ORDERS_START',
    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAIL: 'FETCH_ORDERS_FAIL',
    AUTH_CHECK_STATE: 'AUTH_CHECK_STATE',
    AUTH_USER: 'AUTH_USER',
    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    AUTH_CHECK_TIMEOUT: 'AUTH_CHECK_TIMEOUT',
    AUTH_INITIATE_LOGOUT: 'AUTH_INITIATE_LOGOUT',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    SET_AUTH_REDIRECT_PATH: 'SET_AUTH_REDIRECT_PATH'
};
export default actionTypes;